export enum AttributeEnum {
    STRENGTH = "STRENGTH",
    SPEED = "SPEED",
    JUMP = "JUMP",
    STAMINA = "STAMINA",
    INSIDE_SHOT = "INSIDE_SHOT",
    DUNK = "DUNK",
    FREE_THROW = "FREE_THROW",
    MID_RANGE_SHOT = "MID_RANGE_SHOT",
    THREE_POINT_SHOT = "THREE_POINT_SHOT",
    PASSING = "PASSING",
    BALL_CONTROL = "BALL_CONTROL",
    OFFENSIVE_IQ = "OFFENSIVE_IQ",
    DEFENSIVE_IQ = "DEFENSIVE_IQ",
    DEFENSIVE_REBOUND = "DEFENSIVE_REBOUND",
    REBOUNDING = "REBOUNDING",
}

export const AttributeLabelMap = {
    [AttributeEnum.STRENGTH]: "Strength",
    [AttributeEnum.SPEED]: "Speed",
    [AttributeEnum.JUMP]: "Jump",
    [AttributeEnum.STAMINA]: "Stamina",
    [AttributeEnum.INSIDE_SHOT]: "Inside shot",
    [AttributeEnum.DUNK]: "Dunk",
    [AttributeEnum.FREE_THROW]: "Free Throw",
    [AttributeEnum.MID_RANGE_SHOT]: "Midrange Shot",
    [AttributeEnum.THREE_POINT_SHOT]: "3PT Shot",
    [AttributeEnum.PASSING]: "Passing",
    [AttributeEnum.BALL_CONTROL]: "Ball Control",
    [AttributeEnum.OFFENSIVE_IQ]: "Offensive IQ",
    [AttributeEnum.DEFENSIVE_IQ]: "Defensive IQ",
    [AttributeEnum.DEFENSIVE_REBOUND]: "Defensive Rebound",
    [AttributeEnum.REBOUNDING]: "Rebounding",
}